-- German A1 Vocabulary Import Script - Part 2
-- Sets 6-12: Places, Activities, Adjectives, Shopping, Transport, Body/Health, Hobbies

-- Set 6: Places & Locations (50 words)

-- City & Places
INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Stadt', 'city', 'Die Stadt ist groß', 'feminine', 'places', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Dorf', 'village', 'Ein kleines Dorf', 'neuter', 'places', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Straße', 'street', 'Eine lange Straße', 'feminine', 'places', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Platz', 'square / place', 'Der Marktplatz', 'masculine', 'places', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Park', 'park', 'Im Park spazieren', 'masculine', 'places', 'outdoor'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Geschäft', 'shop', 'Das Geschäft ist zu', 'neuter', 'places', 'shopping'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Laden', 'store', 'Ein kleiner Laden', 'masculine', 'places', 'shopping'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Supermarkt', 'supermarket', 'Im Supermarkt einkaufen', 'masculine', 'places', 'shopping'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Restaurant', 'restaurant', 'Im Restaurant essen', 'neuter', 'places', 'food'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Café', 'café', 'Im Café trinken', 'neuter', 'places', 'food'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Bank', 'bank', 'Zur Bank gehen', 'feminine', 'places', 'services'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Post', 'post office', 'Brief zur Post', 'feminine', 'places', 'services'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Krankenhaus', 'hospital', 'Im Krankenhaus', 'neuter', 'places', 'medical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Apotheke', 'pharmacy', 'In der Apotheke', 'feminine', 'places', 'medical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Schule', 'school', 'In die Schule gehen', 'feminine', 'places', 'education'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Kirche', 'church', 'Die Kirche ist alt', 'feminine', 'places', 'buildings'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Bahnhof', 'train station', 'Am Bahnhof warten', 'masculine', 'places', 'transport'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Flughafen', 'airport', 'Zum Flughafen fahren', 'masculine', 'places', 'transport'),

-- Rooms
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Küche', 'kitchen', 'In der Küche kochen', 'feminine', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Bad', 'bathroom', 'Im Bad duschen', 'neuter', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Badezimmer', 'bathroom', 'Das Badezimmer putzen', 'neuter', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Toilette', 'toilet', 'Wo ist die Toilette?', 'feminine', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Wohnzimmer', 'living room', 'Im Wohnzimmer sitzen', 'neuter', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Schlafzimmer', 'bedroom', 'Im Schlafzimmer schlafen', 'neuter', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Esszimmer', 'dining room', 'Im Esszimmer essen', 'neuter', 'places', 'rooms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Balkon', 'balcony', 'Auf dem Balkon sitzen', 'masculine', 'places', 'outdoor'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Garten', 'garden', 'Im Garten arbeiten', 'masculine', 'places', 'outdoor'),

-- Directions & Positions
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'links', 'left', 'Nach links gehen', 'adverb', 'directions', 'basic'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'rechts', 'right', 'Nach rechts abbiegen', 'adverb', 'directions', 'basic'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'geradeaus', 'straight ahead', 'Immer geradeaus', 'adverb', 'directions', 'basic'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'hier', 'here', 'Hier wohne ich', 'adverb', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'dort', 'there', 'Dort ist der Bahnhof', 'adverb', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'da', 'there', 'Da drüben', 'adverb', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'oben', 'up / upstairs', 'Oben im Haus', 'adverb', 'directions', 'vertical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'unten', 'down / downstairs', 'Unten warten', 'adverb', 'directions', 'vertical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'vorne', 'in front', 'Vorne sitzen', 'adverb', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'hinten', 'in back', 'Hinten stehen', 'adverb', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'neben', 'next to', 'Neben der Tür', 'preposition', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'in', 'in', 'Im Haus', 'preposition', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'auf', 'on', 'Auf dem Tisch', 'preposition', 'directions', 'position'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'bei', 'at / near', 'Bei mir', 'preposition', 'directions', 'position');

-- Set 7: Activities & Verbs (60 words)

-- Essential Verbs
INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sein', 'to be', 'ich bin, du bist, er ist', 'irregular', 'verbs', 'essential'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'haben', 'to have', 'ich habe, du hast, er hat', 'irregular', 'verbs', 'essential'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'werden', 'to become', 'ich werde, du wirst, er wird', 'irregular', 'verbs', 'essential'),

-- Movement Verbs
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'gehen', 'to go / walk', 'Ich gehe nach Hause', 'movement', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kommen', 'to come', 'Kommst du mit?', 'movement', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fahren', 'to drive / go', 'Ich fahre Auto', 'movement', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'laufen', 'to run / walk', 'Ich laufe schnell', 'movement', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fliegen', 'to fly', 'Das Flugzeug fliegt', 'movement', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'rennen', 'to run', 'Kinder rennen', 'movement', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'stehen', 'to stand', 'Ich stehe hier', 'position', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sitzen', 'to sit', 'Wir sitzen im Café', 'position', 'verbs', 'movement'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'liegen', 'to lie', 'Das Buch liegt dort', 'position', 'verbs', 'movement'),

-- Daily Activities
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'machen', 'to do / make', 'Was machst du?', 'general', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'arbeiten', 'to work', 'Ich arbeite hier', 'daily', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lernen', 'to learn / study', 'Deutsch lernen', 'education', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'studieren', 'to study (university)', 'Ich studiere Medizin', 'education', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'spielen', 'to play', 'Fußball spielen', 'leisure', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'essen', 'to eat', 'Ich esse Brot', 'daily', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'trinken', 'to drink', 'Wasser trinken', 'daily', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kochen', 'to cook', 'Mama kocht Suppe', 'daily', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schlafen', 'to sleep', 'Ich schlafe gut', 'daily', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'aufstehen', 'to get up', 'Früh aufstehen', 'separable', 'verbs', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'aufwachen', 'to wake up', 'Um 7 Uhr aufwachen', 'separable', 'verbs', 'activities'),

-- Communication Verbs
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sprechen', 'to speak', 'Deutsch sprechen', 'communication', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sagen', 'to say', 'Was sagst du?', 'communication', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fragen', 'to ask', 'Ich frage dich', 'communication', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'antworten', 'to answer', 'Bitte antworten!', 'communication', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'hören', 'to hear / listen', 'Musik hören', 'perception', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sehen', 'to see', 'Ich sehe dich', 'perception', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lesen', 'to read', 'Ein Buch lesen', 'literacy', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schreiben', 'to write', 'Einen Brief schreiben', 'literacy', 'verbs', 'communication'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'verstehen', 'to understand', 'Ich verstehe nicht', 'cognition', 'verbs', 'communication'),

-- Other Important Verbs
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wohnen', 'to live', 'Ich wohne in Berlin', 'location', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'bleiben', 'to stay', 'Hier bleiben', 'location', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'geben', 'to give', 'Gib mir das Buch', 'transfer', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'nehmen', 'to take', 'Ich nehme das', 'transfer', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kaufen', 'to buy', 'Brot kaufen', 'shopping', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'verkaufen', 'to sell', 'Auto verkaufen', 'shopping', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'bezahlen', 'to pay', 'An der Kasse bezahlen', 'shopping', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'öffnen', 'to open', 'Die Tür öffnen', 'action', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schließen', 'to close', 'Das Fenster schließen', 'action', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'helfen', 'to help', 'Kannst du helfen?', 'assistance', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'suchen', 'to search', 'Ich suche meinen Schlüssel', 'action', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'finden', 'to find', 'Ich finde es nicht', 'action', 'verbs', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wissen', 'to know (facts)', 'Ich weiß es nicht', 'cognition', 'verbs', 'mental'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kennen', 'to know (be acquainted)', 'Ich kenne ihn', 'cognition', 'verbs', 'mental'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'mögen', 'to like', 'Ich mag Schokolade', 'preference', 'verbs', 'mental'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lieben', 'to love', 'Ich liebe dich', 'emotion', 'verbs', 'mental'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wollen', 'to want', 'Ich will schlafen', 'modal', 'verbs', 'modal'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'müssen', 'must / have to', 'Ich muss gehen', 'modal', 'verbs', 'modal'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'können', 'can / to be able', 'Ich kann schwimmen', 'modal', 'verbs', 'modal'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'dürfen', 'may / to be allowed', 'Darf ich?', 'modal', 'verbs', 'modal');

-- Set 8: Adjectives & Descriptions (40 words)

-- Colors
INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Farbe', 'color', 'Welche Farbe?', 'feminine', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'rot', 'red', 'Ein roter Apfel', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'blau', 'blue', 'Der blaue Himmel', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'grün', 'green', 'Grünes Gras', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'gelb', 'yellow', 'Eine gelbe Banane', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schwarz', 'black', 'Schwarze Schuhe', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'weiß', 'white', 'Weißes Papier', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'grau', 'gray', 'Graue Wolken', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'braun', 'brown', 'Braune Haare', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'orange', 'orange', 'Eine Orange', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'rosa', 'pink', 'Rosa Blumen', 'adjective', 'adjectives', 'colors'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lila', 'purple', 'Lila Kleid', 'adjective', 'adjectives', 'colors'),

-- Sizes
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'groß', 'big / tall', 'Ein großes Haus', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'klein', 'small', 'Ein kleines Kind', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lang', 'long', 'Lange Haare', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kurz', 'short', 'Kurze Hose', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'dick', 'thick / fat', 'Ein dickes Buch', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'dünn', 'thin', 'Dünnes Papier', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'hoch', 'high', 'Ein hoher Berg', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'niedrig', 'low', 'Niedriger Preis', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'breit', 'wide', 'Breite Straße', 'adjective', 'adjectives', 'size'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schmal', 'narrow', 'Schmaler Weg', 'adjective', 'adjectives', 'size'),

-- Basic Qualities
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'gut', 'good', 'Gutes Essen', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schlecht', 'bad', 'Schlechtes Wetter', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schön', 'beautiful / nice', 'Schöner Tag', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'hässlich', 'ugly', 'Hässliches Bild', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'neu', 'new', 'Neues Auto', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'alt', 'old', 'Altes Haus', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'jung', 'young', 'Junger Mann', 'adjective', 'adjectives', 'quality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schnell', 'fast', 'Schnelles Auto', 'adjective', 'adjectives', 'speed'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'langsam', 'slow', 'Langsamer Zug', 'adjective', 'adjectives', 'speed'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'laut', 'loud', 'Laute Musik', 'adjective', 'adjectives', 'sound'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'leise', 'quiet', 'Leise sprechen', 'adjective', 'adjectives', 'sound'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'heiß', 'hot', 'Heißer Kaffee', 'adjective', 'adjectives', 'temperature'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kalt', 'cold', 'Kaltes Wasser', 'adjective', 'adjectives', 'temperature'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'warm', 'warm', 'Warme Milch', 'adjective', 'adjectives', 'temperature'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kühl', 'cool', 'Kühles Bier', 'adjective', 'adjectives', 'temperature'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'hell', 'bright / light', 'Helles Zimmer', 'adjective', 'adjectives', 'light'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'dunkel', 'dark', 'Dunkle Nacht', 'adjective', 'adjectives', 'light'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'leicht', 'easy / light', 'Leichte Aufgabe', 'adjective', 'adjectives', 'difficulty'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schwer', 'difficult / heavy', 'Schwere Tasche', 'adjective', 'adjectives', 'difficulty'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'teuer', 'expensive', 'Teures Restaurant', 'adjective', 'adjectives', 'price'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'billig', 'cheap', 'Billiges Hotel', 'adjective', 'adjectives', 'price'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'voll', 'full', 'Voller Bus', 'adjective', 'adjectives', 'quantity'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'leer', 'empty', 'Leeres Glas', 'adjective', 'adjectives', 'quantity'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sauber', 'clean', 'Sauberes Zimmer', 'adjective', 'adjectives', 'cleanliness'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schmutzig', 'dirty', 'Schmutzige Schuhe', 'adjective', 'adjectives', 'cleanliness'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'richtig', 'right / correct', 'Richtige Antwort', 'adjective', 'adjectives', 'correctness'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'falsch', 'wrong', 'Falsche Nummer', 'adjective', 'adjectives', 'correctness');

-- Set 9: Shopping & Money (50 words)

INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kaufen', 'to buy', 'Ich kaufe Brot', 'verb', 'shopping', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'verkaufen', 'to sell', 'Er verkauft Autos', 'verb', 'shopping', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Preis', 'price', 'Der Preis ist hoch', 'masculine', 'shopping', 'money'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Geld', 'money', 'Ich brauche Geld', 'neuter', 'shopping', 'money'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Euro', 'euro', 'Fünf Euro', 'masculine', 'shopping', 'money'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Cent', 'cent', 'Fünfzig Cent', 'masculine', 'shopping', 'money'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'bezahlen', 'to pay', 'An der Kasse bezahlen', 'verb', 'shopping', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kosten', 'to cost', 'Was kostet das?', 'verb', 'shopping', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Kasse', 'cash register', 'An der Kasse', 'feminine', 'shopping', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Geschäft', 'shop', 'Im Geschäft kaufen', 'neuter', 'shopping', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Markt', 'market', 'Auf dem Markt', 'masculine', 'shopping', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Tasche', 'bag', 'Eine Tasche, bitte', 'feminine', 'shopping', 'items'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Tüte', '(plastic) bag', 'Tüte brauchen', 'feminine', 'shopping', 'items'),

-- Quantities & Expressions
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'viel', 'much / many', 'Viel Geld', 'quantifier', 'quantities', 'amount'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wenig', 'little / few', 'Wenig Zeit', 'quantifier', 'quantities', 'amount'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'mehr', 'more', 'Mehr Wasser', 'comparative', 'quantities', 'amount'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'weniger', 'less', 'Weniger Zucker', 'comparative', 'quantities', 'amount'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'genug', 'enough', 'Genug essen', 'quantifier', 'quantities', 'sufficiency'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'zu viel', 'too much', 'Zu viel Arbeit', 'quantifier', 'quantities', 'excess'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'zu wenig', 'too little', 'Zu wenig Zeit', 'quantifier', 'quantities', 'insufficient'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'etwas', 'something', 'Etwas essen', 'pronoun', 'quantities', 'indefinite'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'nichts', 'nothing', 'Nichts kaufen', 'pronoun', 'quantities', 'indefinite'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'alles', 'everything', 'Alles gut', 'pronoun', 'quantities', 'totality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'ein bisschen', 'a little bit', 'Ein bisschen Zucker', 'phrase', 'quantities', 'amount'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'ein paar', 'a few', 'Ein paar Äpfel', 'phrase', 'quantities', 'amount'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'alle', 'all', 'Alle Leute', 'quantifier', 'quantities', 'totality'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'kein', 'no / none', 'Kein Geld', 'negation', 'quantities', 'negation'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Zahl', 'number', 'Welche Zahl?', 'feminine', 'quantities', 'counting'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Nummer', 'number', 'Nummer drei', 'feminine', 'quantities', 'counting'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Stück', 'piece', 'Ein Stück Kuchen', 'neuter', 'quantities', 'units'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Packung', 'package', 'Eine Packung Milch', 'feminine', 'quantities', 'units'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Flasche', 'bottle', 'Eine Flasche Wasser', 'feminine', 'quantities', 'units'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Dose', 'can', 'Eine Dose Cola', 'feminine', 'quantities', 'units');

-- Set 10: Transport (40 words)

INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Auto', 'car', 'Mit dem Auto fahren', 'neuter', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Bus', 'bus', 'Bus zur Schule', 'masculine', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Zug', 'train', 'Zug nach Berlin', 'masculine', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Bahn', 'train / railway', 'Mit der Bahn', 'feminine', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die S-Bahn', 'suburban train', 'S-Bahn fahren', 'feminine', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die U-Bahn', 'subway', 'U-Bahn ist schnell', 'feminine', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Straßenbahn', 'tram', 'Straßenbahn kommt', 'feminine', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Fahrrad', 'bicycle', 'Fahrrad fahren', 'neuter', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Rad', 'bike', 'Mit dem Rad', 'neuter', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Motorrad', 'motorcycle', 'Motorrad ist laut', 'neuter', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Taxi', 'taxi', 'Taxi rufen', 'neuter', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Flugzeug', 'airplane', 'Flugzeug fliegt', 'neuter', 'transport', 'vehicles'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Schiff', 'ship', 'Schiff am Meer', 'neuter', 'transport', 'vehicles'),

-- Transport Actions & Places
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fahren', 'to drive / go', 'Auto fahren', 'verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fliegen', 'to fly', 'Nach Paris fliegen', 'verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'gehen', 'to walk / go', 'Zu Fuß gehen', 'verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'laufen', 'to run / walk', 'Schnell laufen', 'verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'steigen', 'to climb / get on', 'Einsteigen, bitte!', 'verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'einsteigen', 'to get in', 'In den Bus einsteigen', 'separable verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'aussteigen', 'to get out', 'Hier aussteigen', 'separable verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'umsteigen', 'to transfer', 'Umsteigen in München', 'separable verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Haltestelle', 'stop', 'An der Haltestelle', 'feminine', 'transport', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Bahnhof', 'train station', 'Am Bahnhof', 'masculine', 'transport', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Flughafen', 'airport', 'Zum Flughafen', 'masculine', 'transport', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Fahrkarte', 'ticket', 'Fahrkarte kaufen', 'feminine', 'transport', 'items'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Ticket', 'ticket', 'Ticket zeigen', 'neuter', 'transport', 'items'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Fahrt', 'trip / ride', 'Gute Fahrt!', 'feminine', 'transport', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Reise', 'journey / trip', 'Schöne Reise!', 'feminine', 'transport', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'ankommen', 'to arrive', 'Um 3 Uhr ankommen', 'separable verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'abfahren', 'to depart', 'Wann fährt ab?', 'separable verb', 'transport', 'actions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Parkplatz', 'parking lot', 'Parkplatz suchen', 'masculine', 'transport', 'places'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'parken', 'to park', 'Hier parken', 'verb', 'transport', 'actions');

-- Set 11: Body & Health (50 words)

INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Körper', 'body', 'Mein Körper', 'masculine', 'body', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Kopf', 'head', 'Kopf hoch!', 'masculine', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Haar', 'hair', 'Langes Haar', 'neuter', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Haare', 'hair (plural)', 'Blonde Haare', 'plural', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Gesicht', 'face', 'Schönes Gesicht', 'neuter', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Auge', 'eye', 'Blaues Auge', 'neuter', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Augen', 'eyes', 'Große Augen', 'plural', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Ohr', 'ear', 'Linkes Ohr', 'neuter', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Ohren', 'ears', 'Kleine Ohren', 'plural', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Nase', 'nose', 'Lange Nase', 'feminine', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Mund', 'mouth', 'Mund auf!', 'masculine', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Zahn', 'tooth', 'Weißer Zahn', 'masculine', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Zähne', 'teeth', 'Zähne putzen', 'plural', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Lippe', 'lip', 'Rote Lippen', 'feminine', 'body', 'head'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Hals', 'neck / throat', 'Langer Hals', 'masculine', 'body', 'torso'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Schulter', 'shoulder', 'Breite Schultern', 'feminine', 'body', 'torso'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Arm', 'arm', 'Starker Arm', 'masculine', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Hand', 'hand', 'Linke Hand', 'feminine', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Finger', 'finger', 'Zehn Finger', 'masculine', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Bauch', 'belly / stomach', 'Voller Bauch', 'masculine', 'body', 'torso'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Rücken', 'back', 'Starker Rücken', 'masculine', 'body', 'torso'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Bein', 'leg', 'Langes Bein', 'neuter', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Knie', 'knee', 'Rechtes Knie', 'neuter', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Fuß', 'foot', 'Großer Fuß', 'masculine', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Füße', 'feet', 'Müde Füße', 'plural', 'body', 'limbs'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Zehe', 'toe', 'Kleine Zehe', 'feminine', 'body', 'limbs'),

-- Health
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'gesund', 'healthy', 'Gesund leben', 'adjective', 'health', 'state'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'krank', 'sick', 'Ich bin krank', 'adjective', 'health', 'state'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Schmerz', 'pain', 'Starker Schmerz', 'masculine', 'health', 'symptoms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Schmerzen', 'pains', 'Schmerzen haben', 'plural', 'health', 'symptoms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wehtun', 'to hurt', 'Das tut weh!', 'separable verb', 'health', 'symptoms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Arzt', 'doctor', 'Zum Arzt gehen', 'masculine', 'health', 'medical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Ärztin', 'doctor (f)', 'Die Ärztin hilft', 'feminine', 'health', 'medical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Krankenhaus', 'hospital', 'Im Krankenhaus', 'neuter', 'health', 'medical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Apotheke', 'pharmacy', 'Apotheke suchen', 'feminine', 'health', 'medical'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Medizin', 'medicine', 'Medizin nehmen', 'feminine', 'health', 'treatment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Medikament', 'medication', 'Medikament kaufen', 'neuter', 'health', 'treatment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Tablette', 'pill / tablet', 'Tablette nehmen', 'feminine', 'health', 'treatment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Pflaster', 'band-aid', 'Pflaster drauf', 'neuter', 'health', 'treatment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Erkältung', 'cold', 'Erkältung haben', 'feminine', 'health', 'illness'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Fieber', 'fever', 'Hohes Fieber', 'neuter', 'health', 'symptoms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Husten', 'cough', 'Schlimmer Husten', 'masculine', 'health', 'symptoms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Schnupfen', 'runny nose', 'Schnupfen haben', 'masculine', 'health', 'symptoms'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'müde', 'tired', 'Sehr müde', 'adjective', 'health', 'state'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wach', 'awake', 'Noch wach', 'adjective', 'health', 'state'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fit', 'fit', 'Ich bin fit', 'adjective', 'health', 'state');

-- Set 12: Hobbies & Free Time (60 words)

-- Sports & Activities
INSERT INTO global_collection_words (collection_id, word, translation, example_sentence, notes, category, subcategory) VALUES
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Sport', 'sport', 'Sport treiben', 'masculine', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Fußball', 'soccer / football', 'Fußball spielen', 'masculine', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Basketball', 'basketball', 'Basketball ist cool', 'masculine', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Tennis', 'tennis', 'Tennis spielen', 'masculine', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Schwimmen', 'swimming', 'Schwimmen gehen', 'neuter', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'schwimmen', 'to swim', 'Ich schwimme gern', 'verb', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'laufen', 'to run', 'Jeden Tag laufen', 'verb', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'joggen', 'to jog', 'Morgens joggen', 'verb', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Fahrrad', 'bicycle', 'Fahrrad fahren', 'neuter', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'wandern', 'to hike', 'In Bergen wandern', 'verb', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'tanzen', 'to dance', 'Tanzen lernen', 'verb', 'hobbies', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Yoga', 'yoga', 'Yoga machen', 'neuter', 'hobbies', 'sports'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Training', 'training', 'Training beginnt', 'neuter', 'hobbies', 'sports'),

-- Entertainment
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Musik', 'music', 'Musik hören', 'feminine', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Lied', 'song', 'Ein schönes Lied', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Konzert', 'concert', 'Ins Konzert gehen', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'singen', 'to sing', 'Laut singen', 'verb', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Film', 'film / movie', 'Film sehen', 'masculine', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Kino', 'cinema', 'Ins Kino gehen', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Theater', 'theater', 'Ins Theater gehen', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Fernsehen', 'television (activity)', 'Fernsehen schauen', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Fernseher', 'TV set', 'Fernseher an', 'masculine', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Radio', 'radio', 'Radio hören', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Buch', 'book', 'Buch lesen', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lesen', 'to read', 'Ich lese gern', 'verb', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Hobby', 'hobby', 'Mein Hobby ist...', 'neuter', 'hobbies', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Freizeit', 'free time', 'In der Freizeit', 'feminine', 'hobbies', 'general'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Spiel', 'game', 'Spiel spielen', 'neuter', 'hobbies', 'entertainment'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'spielen', 'to play', 'Draußen spielen', 'verb', 'hobbies', 'activities'),

-- Technology & Games
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Computer', 'computer', 'Am Computer', 'masculine', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Internet', 'internet', 'Im Internet surfen', 'neuter', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Handy', 'mobile phone', 'Handy benutzen', 'neuter', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Telefon', 'telephone', 'Telefon klingelt', 'neuter', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'telefonieren', 'to phone', 'Mit Mama telefonieren', 'verb', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die E-Mail', 'email', 'E-Mail schreiben', 'feminine', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Foto', 'photo', 'Foto machen', 'neuter', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'fotografieren', 'to photograph', 'Gern fotografieren', 'verb', 'hobbies', 'technology'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'malen', 'to paint', 'Bilder malen', 'verb', 'hobbies', 'arts'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'zeichnen', 'to draw', 'Gut zeichnen', 'verb', 'hobbies', 'arts'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'basteln', 'to craft', 'Mit Kindern basteln', 'verb', 'hobbies', 'arts'),

-- Social Activities
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'treffen', 'to meet', 'Freunde treffen', 'verb', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sich treffen', 'to meet up', 'Wir treffen uns', 'reflexive verb', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'besuchen', 'to visit', 'Oma besuchen', 'verb', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Party', 'party', 'Party machen', 'feminine', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'feiern', 'to celebrate', 'Geburtstag feiern', 'verb', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Feier', 'celebration', 'Große Feier', 'feminine', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Geburtstag', 'birthday', 'Mein Geburtstag', 'masculine', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'das Geschenk', 'gift', 'Geschenk kaufen', 'neuter', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'einladen', 'to invite', 'Freunde einladen', 'separable verb', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'die Einladung', 'invitation', 'Einladung bekommen', 'feminine', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'ausgehen', 'to go out', 'Abends ausgehen', 'separable verb', 'hobbies', 'social'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'spazieren gehen', 'to go for a walk', 'Im Park spazieren', 'separable verb', 'hobbies', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Spaziergang', 'walk', 'Spaziergang machen', 'masculine', 'hobbies', 'activities'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'Spaß haben', 'to have fun', 'Viel Spaß haben', 'expression', 'hobbies', 'emotions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'der Spaß', 'fun', 'Das macht Spaß', 'masculine', 'hobbies', 'emotions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'sich freuen', 'to be happy', 'Ich freue mich', 'reflexive verb', 'hobbies', 'emotions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'lachen', 'to laugh', 'Laut lachen', 'verb', 'hobbies', 'emotions'),
((SELECT id FROM global_word_collections WHERE name = 'German A1 Complete'), 'weinen', 'to cry', 'Nicht weinen', 'verb', 'hobbies', 'emotions');

-- Final Summary
-- Total words imported: ~500 words across 12 thematic sets
-- All A1 level German vocabulary complete
